version: '3'

services:
  web-app-client:
    build: 
      context: ../../
      dockerfile: "deploy/docker/Dockerfile"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
